name: Issue to Pull Request

on:
  issue_comment:
    types: [created]

jobs:
  create_pr:
    if: github.event.issue.number == 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Convert issue to JSON
        id: convert
        run: |
          echo "github.event.issue: ${{ github.event.comment }}"
          echo "toJson output: ${{ toJson(github.event.comment) }}"
          node convert-issue.js "$(echo '${{ toJson(github.event.comment) }}')"
          echo "issue_number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT

      - name: Create branch or checkout if exists
        run: |
          git show-ref --verify --quiet refs/heads/add_new_data && git checkout add_new_data || git checkout -b add_new_data

      - name: Configure Git user
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "${{ github.event.comment.user.login }}"

      - name: Commit changes
        run: |
          git add assets/issue-${{ steps.convert.outputs.issue_number }}.json
          git commit -m "Add issue #${{ steps.convert.outputs.issue_number }} as JSON"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: add_new_data
          force: true

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add issue #${{ steps.convert.outputs.issue_number }} as JSON"
          title: "Issue #${{ steps.convert.outputs.issue_number }} as JSON"
          body: "This pull request automatically converts issue #${{ steps.convert.outputs.issue_number }} to a JSON file."
          branch: add_new_data
          base: develop
